version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: earthmars-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - earthmars_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis

  vote:
    build: ./vote-java
    container_name: vote
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_LIST: votes
    ports:
      - "8080:8080"
    depends_on:
      - redis

  worker:
    build: ./worker-dotnet
    container_name: worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_LIST: votes
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  result:
    build: ./result-node
    container_name: result
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  earthmars_pgdata:
