<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Provides BackgroundService, Host, logging, config -->
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    
    <!-- PostgreSQL client -->
    <PackageReference Include="Npgsql" Version="8.0.5" />
  </ItemGroup>

</Project>
